### ISSUE TITLE
Addin depedency verification.

### ISSUE THREAD

**Issue by matthewrdev** [matthewrdev/monodevelop-addin-packager#4]
As part of the packaging process, a validation step should be added that ensures that the user has added tags for each project and external assembly reference (IE: Ones that aren't in the GAC).

Further work would be to just generate the required import elements into the AddinInfo.cs file like so:
[assembly:ImportAddinAssembly("assemly.dll")]

**Comment by matthew-ch-robbins** [comment]
Suggest implementing a compiler error.
