### ISSUE TITLE
Xamarin Studio vs. MonoDevelop

### ISSUE THREAD

**Issue by sushihangover** [matthewrdev/monodevelop-addin-packager#7]
I am working on Addins for [PlayScript](https://github.com/PlayScriptRedux/playscript) and use both Xam arian Studio and MonoDevelop.

Is this Addin's requirement MonoAndroid and Xamarin.Ide required?

Note: I am only seeing MonoDevelop.Ide refs, not sure where the references from the screenshot below are coming from:

![screen shot 2015-11-01 at 2 25 23 am](https://cloud.githubusercontent.com/assets/1294194/10868323/36ea3124-8040-11e5-8962-fd1ff654773c.png)

**Comment by matthewrdev** [comment]
No they should not be. I'll strip the dependencies out and push an update.

**Comment by matthewrdev** [comment]
New version should be out soon, I'll leave this open for you to confirm and close @sushihangover

**Comment by matthewrdev** [comment]
PS: I normally broadcast when I make a new build on twitter. My handle is ["@matthewrdev"](https://twitter.com/matthewrdev)

**Comment by sushihangover** [comment]
Thanks, I give a a try in the next day or so...
