### ISSUE TITLE
Xamarin Install/Uninstall Failure

### ISSUE THREAD

**Issue by CalebMorris** [matthewrdev/monodevelop-addin-packager#8]
When installing/uninstalling (v2.5.0) in Xamarin (v5.9.8 build 0) the process fails when unable to handle description. The add-in installs and just requires a full restart of Xamarin.

On a side note: while the add-in is shown as install on restart and are in the correct location I cannot find the commands for packaging anywhere (under any context menu or full menu).

![screenshot 2015-11-01 20 46 20](https://cloud.githubusercontent.com/assets/347395/10873961/be5faa82-80d9-11e5-9690-671860fa92e6.png)

**Comment by matthewrdev** [comment]
@CalebMorris Do you have the AddinMaker installed also? If so, what version?

**Comment by matthewrdev** [comment]
Reproduced in Xamarin Studio 5.9.8, noted that this uses v1.2.1 of the Addin Maker. A restart of Xamarin Studio seemed to make the commands re-appear under the "Project" menu.

**Comment by CalebMorris** [comment]
Did a reinstall with the changes. Installed cleanly and commands show up.
Thanks.
