### ISSUE TITLE
Project Dependencies

### ISSUE THREAD

**Issue by CalebMorris** [matthewrdev/monodevelop-addin-packager#9]
I am creating a plugin that I am splitting across a couple projects to reuse some of the code I need for a later project, but I can't find a way to get the packager to pull in the local project `.dll` other than the root package dll.
I've tried a bunch of different things through `mdtool` to no avail as every dependency is treated like it should be an addin on its own.

Do you know if this functionality exists with the packager or with `mdtool`?

**Comment by matthewrdev** [comment]
From what you're describing you need to register each dll as an AddinDependency. This is a sample of my other addin's depenedency file:

**Addin.Assemblies.cs**

	using Mono.Addins;

	// Dependencies
	[assembly:ImportAddinAssembly("Parse.dll")]
	[assembly:ImportAddinAssembly("Parse.NetFx45.dll")]
	[assembly:ImportAddinAssembly("MFractor.Library.dll")]
	[assembly:ImportAddinAssembly("MFractor.Licensing.dll")]
	[assembly:ImportAddinAssembly("AndroidResourceIndexer.dll")]
	[assembly:ImportAddinAssembly("Logging.dll")]

Each dll that is referenced by the project that needs to be included in the final mpack file should have a `ImportAddinAssembly` attribute used.

**Comment by matthewrdev** [comment]
Just to note, this is the standard way of bundling dlls into the addin.

**Comment by CalebMorris** [comment]
Perfect.
Is there standard documentation somewhere for constructing add-ins? Every document I have been using from monodevelop and Xamarin is outdated or incredibly vague and have mainly been looking through other add-ins to find out how they work.

**Comment by matthewrdev** [comment]
I feel your pain Caleb, the documentation is pretty crap for building addins. Honestly, that methodology (inspecting other addins source code) seems to be the way to go. It's frustrating but eventually you learn enough that your development cadence is reasonable.

I'd absolutely love to be able to build a knowledge base around what I've learnt from building my other addin. Maybe one day I'll find the time...
